"""Typed, aggregation-safe method failures."""

from __future__ import annotations

from enum import StrEnum


class FailureCode(StrEnum):
    NONE = "NONE"
    INSUFFICIENT_ROWS = "INSUFFICIENT_ROWS"
    TREATMENT_ARM_SUPPORT = "TREATMENT_ARM_SUPPORT"
    RANK_DEFICIENT_DESIGN = "RANK_DEFICIENT_DESIGN"
    SINGULAR_CROSSPRODUCT = "SINGULAR_CROSSPRODUCT"
    HC3_UNDEFINED_PERFECT_LEVERAGE = "HC3_UNDEFINED_PERFECT_LEVERAGE"
    NONFINITE_ESTIMATE = "NONFINITE_ESTIMATE"
    NO_OBSERVED_VALUES_FOR_IMPUTATION = "NO_OBSERVED_VALUES_FOR_IMPUTATION"
    IMPUTATION_RANK_FAILURE = "IMPUTATION_RANK_FAILURE"
    HUBER_SCALE_FAILURE = "HUBER_SCALE_FAILURE"
    HUBER_NONCONVERGENCE = "HUBER_NONCONVERGENCE"
